Algoritmo "OlaMundo"
// -------------------------------------------------
// Algoritmo para escrever olá, mundo.
//
// AUTOR: Jean Lucas de O. Straub
// Curso de Algoritmos da Plataforma Curso em Vídeo.
// Professor: Gustavo Guanabara
// -------------------------------------------------
Var
   msg:caractere
   i:inteiro
Inicio
   msg <- "OLÁ, MUNDO"
   
   para i <- 1 ate 10 faca
      Escreva(copia(msg,i,1))
   fimpara


Fimalgoritmo