Algoritmo "Qualseunome"
// -------------------------------------------------
// Algoritmo para ler o nome do usuário.
//
// AUTOR: Jean Lucas
// Curso de Algoritmos da Plataforma Curso em Vídeo.
// Professor: Gustavo Guanabara
// -------------------------------------------------
Var
   nome:caractere
Inicio
   Escreval(" >.< - Digite seu nome: ")
   Escreva(" YOU - ")
   Leia(nome)
   
   Escreva(" >.< - Seja muito bem-vindo(a) ",nome)


Fimalgoritmo